dist: xenial
language: python
python:
  - "3.8"

before_script:
  - pip install -r requirements.txt
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

env:
  - DJANGO_SETTINGS_MODULE="config.settings.travis"
  - DATABASE_NAME=postgres
  - SECRET_KEY="p1-o$9l&0vl4k5t9cima%yxiv!l6m=-^2ji+letn40h^+99*b8"
  - DATABASE_USER=postgres
  - DATABASE_PASS=""
  - DATABASE_HOST=""
  - ENVIRONMENT="dev"
  - IP=""
  - URL1=""
  - URL2=""

services:
  - postgresql
  - xvfb

script:
  - pytest -v