# This is a basic workflow to help you get started with Actions

name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latst
    steps:
      - name: deploy p13
        uses: appleboy/ssh-action@v)0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USENAME}}

          script: |
            cd p13_atmosberry2
            git pull
            echo "Git pull done"
